In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

plt.rcParams['font.family'] = 'NanumGothic'

In [2]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE

from sklearn.datasets import make_classification
from collections import Counter

from matplotlib import pyplot as plt
import seaborn as sns

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
minor_s = pd.read_csv('./drive/MyDrive/공유문서함/상장csv/240317상장비주력_stand.csv', index_col=0)
minor_test = pd.read_csv('./drive/MyDrive/공유문서함/상장csv/240318상장비주력test_stand.csv', index_col=0)

##### train_df, test_df 설정

In [5]:
train_df = minor_s[['유보액대비율', '총자본투자효율', '지급이자율',
 '당좌자산회전률', '자본', '매입채무회전률','매입채무회전기간',
 '자기자본순이익률', '매출채권회전률', '자본분배율', '유연탄가격',
 '타인자본회전률','유보율','부실']]

In [6]:
test_df = minor_test[['유보액대비율', '총자본투자효율', '지급이자율',
 '당좌자산회전률', '자본', '매입채무회전률','매입채무회전기간',
 '자기자본순이익률', '매출채권회전률', '자본분배율', '유연탄가격',
 '타인자본회전률','유보율','부실']]

In [7]:
train_df.reset_index(drop=True,inplace=True)
test_df.reset_index(drop=True,inplace=True)

In [8]:
x_train = train_df.drop("부실",axis=1)
y_train = train_df["부실"]
x_test =test_df.drop("부실",axis=1)
y_test = test_df["부실"]

In [9]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE

In [10]:
from imblearn.under_sampling import RandomUnderSampler

# RandomUnderSampler 객체 생성
under = RandomUnderSampler(random_state=4, sampling_strategy=0.3)

# RandomUnderSampler를 사용하여 샘플링된 특징 및 타겟 데이터 생성
x_resampled, y_resampled = under.fit_resample(x_train, y_train)

In [ ]:
y_resampled.value_counts()

0.0    180
1.0     54
Name: 부실, dtype: int64

In [ ]:
# x_resampled, y_resampled = RandomOverSampler(random_state=4, ).fit_resample(x_train,y_train)
# print(x_train.shape)
# y_train.value_counts()

In [11]:
# 성능확인 코드
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score, average_precision_score

def get_clf_eval(y_test, pred):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    roc_score = roc_auc_score(y_test, pred)
    pr_score = average_precision_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    print('오차행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도 : {1:.4f}, 재현율:{2:.4f},F1 스코어:{3:.4f}'.format(accuracy, precision, recall, f1, roc_score))
    print('ROC 스코어: {0:.4f}, PR score : {1:.4f}'.format(roc_score, pr_score))


##### 교차검증

In [7]:
# fix_list = ['회사명',
#             '회계년도',
#             '설립일',
#             '상장일',
#             '상장폐지일',
#             '상장협 산업분류(소분류)_x',
#             '상장협 산업분류(중분류)_x',
#             '회계년',
#             'Unnamed: 0'
#             ]

def label_split(df):
  # feature = df.drop(fix_list, axis=1)
  feature = df
  label = df['부실']
  return feature, label

In [8]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

def evaluate(y_true, y_pred):
    # 정확도 (Accuracy)
    accuracy = accuracy_score(y_true, y_pred)
    print("Accuracy:", accuracy)

    # 정밀도 (Precision)
    precision = precision_score(y_true, y_pred)
    print("Precision:", precision)

    # 재현율 (Recall)
    recall = recall_score(y_true, y_pred)
    print("Recall:", recall)

    # F1 스코어 (F1 Score)
    f1 = f1_score(y_true, y_pred)
    print("F1 Score:", f1)

    # AUC-ROC
    try:
        auc_roc = roc_auc_score(y_true, y_pred)
        print("AUC-ROC:", auc_roc)
    except ValueError:
        print("AUC-ROC cannot be calculated for multiclass classification.")

In [9]:
!pip install catboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.5/98.5 MB 2.4 MB/s eta 0:00:00


In [18]:
from sklearn.linear_model import LogisticRegression
from catboost import CatBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
import xgboost as xgb
import lightgbm as lgb
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score


def modeling_cv(train, test,threshold=0.5):
    print(train['부실'].value_counts())

    feature, label = label_split(train)
    test_feature, test_label = label_split(test)

    feature, label = label_split(train)
    test_feature, test_label = label_split(test)

    print(label.value_counts())
    print(test_label.value_counts())

    models = [
        # ("Logistic Regression", LogisticRegression()),
        # ("KNN", KNeighborsClassifier(n_neighbors=5)),
        # ("Random Forest", RandomForestClassifier(n_estimators=100, random_state=42)),
        # ("XGBoost", xgb.XGBClassifier()),
        # ("LightGBM", lgb.LGBMClassifier()),
        ("CatBoost", CatBoostClassifier()),
        ("SVM (Linear Kernel)", SVC(kernel='linear', probability=True)),
    ]

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)  # Adjust n_splits as needed

    print("Stratified K-Fold Cross-Validation Performance:")
    for name, model in models:
        print(f"\n---{name}---")
        for train_index, val_index in cv.split(feature, label):
            X_train, X_val = feature.iloc[train_index], feature.iloc[val_index]
            y_train, y_val = label.iloc[train_index], label.iloc[val_index]

            undersampler = RandomUnderSampler(sampling_strategy=0.1, random_state=42)
            X_train_resampled, y_train_resampled = undersampler.fit_resample(X_train, y_train)

            print(y_train_resampled.value_counts())

            model.fit(X_train_resampled, y_train_resampled)  # Train the model on the training fold

            # Use trained model to make predictions on the validation fold
            if hasattr(model, "predict_proba"):
                y_pred_prob = model.predict_proba(X_val)[:, 1]
                y_pred = (y_pred_prob >= threshold).astype(int)  # Apply threshold
            else:
                y_pred = model.predict(X_val)
            print(f"---{name}---")
            evaluate(y_val, y_pred)
            print()

In [19]:
modeling_cv(train_df, test_df,threshold=0.3 )

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
103:	learn: 0.0617022	total: 430ms	remaining: 3.71s
104:	learn: 0.0599818	total: 431ms	remaining: 3.68s
105:	learn: 0.0591961	total: 436ms	remaining: 3.67s
106:	learn: 0.0579325	total: 438ms	remaining: 3.65s
107:	learn: 0.0571806	total: 441ms	remaining: 3.65s
108:	learn: 0.0562099	total: 445ms	remaining: 3.64s
109:	learn: 0.0553812	total: 449ms	remaining: 3.63s
110:	learn: 0.0539185	total: 451ms	remaining: 3.61s
111:	learn: 0.0532176	total: 455ms	remaining: 3.6s
112:	learn: 0.0524595	total: 458ms	remaining: 3.6s
113:	learn: 0.0510473	total: 460ms	remaining: 3.57s
114:	learn: 0.0503355	total: 463ms	remaining: 3.56s
115:	learn: 0.0492803	total: 465ms	remaining: 3.54s
116:	learn: 0.0486798	total: 469ms	remaining: 3.54s
117:	learn: 0.0473918	total: 470ms	remaining: 3.52s
118:	learn: 0.0461460	total: 472ms	remaining: 3.49s
119:	learn: 0.0449411	total: 473ms	remaining: 3.47s
120:	learn: 0.0440218	total: 476ms	remaining: 3.46s
121:	learn: 0.0432395	total: 4

In [15]:
def calculate_f1_score(recall, precision):
    """
    Calculate F1-score using recall and precision.

    Parameters:
    - recall: Recall score.
    - precision: Precision score.

    Returns:
    - f1: F1-score.
    """
    f1 = 2 * (precision * recall) / (precision + recall)
    return f1

In [23]:
# F1-score 계산
f1 = calculate_f1_score(1.0, 1.0)
print("F1-score:", f1)

F1-score: 1.0


In [27]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from imblearn.under_sampling import RandomUnderSampler

# STRAtified k-fold를 위한 설정
k_folds = 5  # k를 설정합니다.
stratified_kfold = StratifiedKFold(n_splits=k_folds, shuffle=True, random_state=42)

# 교차 검증 수행
accuracies = []  # 각 fold의 정확도를 저장할 리스트

for fold, (train_idx, val_idx) in enumerate(stratified_kfold.split(train_df, test_df)):
    print(f"Fold {fold+1}/{k_folds}")

    # Fold에 따라 데이터 분할
    X_train_fold, X_val_fold = train_df.iloc[train_idx], train_df.iloc[val_idx]
    y_train_fold, y_val_fold = test_df.iloc[train_idx], test_df.iloc[val_idx]

    # undersampling 수행
    rus = RandomUnderSampler(sampling_strategy=0.1, random_state=42)
    X_train_resampled, y_train_resampled = rus.fit_resample(X_train_fold, y_train_fold)

    X_train_resampled = X_train_resampled.values.reshape(X_train_resampled.shape[0], 1, X_train_resampled.shape[1])
    y_train_resampled = y_train_resampled.values

    # 모델 생성
    model = Sequential()
    model.add(LSTM(128, activation='relu', input_shape=(X_train_resampled.shape[1:])))
    model.add(Dropout(0.2))
    model.add(Dense(1, activation='sigmoid'))

    # 모델 컴파일
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

    # 모델 학습
    model.fit(X_train_resampled, y_train_resampled, epochs=100, batch_size=64, verbose=0)  # verbose=0으로 설정하여 학습 과정 출력 생략

    # 검증 데이터에 대한 예측 및 평가
    X_val_fold = X_val_fold.values.reshape(X_val_fold.shape[0], 1, X_val_fold.shape[1])
    y_pred = model.predict(X_val_fold)

    # 이진 분류로 변환
    y_pred_binary = (y_pred > 0.3).astype(int)

    evaluate( y_val_fold,y_pred_binary)

ValueError: Found input variables with inconsistent numbers of samples: [3485, 1168]

##### 1. RandomForest

In [12]:
# 랜덤포레스트 구현
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(random_state=52)

rf_clf.fit(x_resampled, y_resampled)
rf_pred = rf_clf.predict(x_test)
rf_pred_proba = rf_clf.predict_proba(x_test)

In [13]:
print("랜덤포레스트")
get_clf_eval(y_test, rf_pred)

랜덤포레스트
오차행렬
[[1156    7]
 [   5    0]]
정확도: 0.9897, 정밀도 : 0.0000, 재현율:0.0000,F1 스코어:0.0000
ROC 스코어: 0.4970, PR score : 0.0043


##### 하이퍼파라미터 조정 & 임계값 설정한 뒤 모델링

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# RandomForestClassifier 모델 생성
rf_clf = RandomForestClassifier()

# 하이퍼파라미터 그리드 설정
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# GridSearchCV를 사용하여 하이퍼파라미터 튜닝과 교차 검증 수행
grid_search = GridSearchCV(rf_clf, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_resampled, y_resampled)

# 최적의 모델과 하이퍼파라미터 가져오기
best_rf_clf = grid_search.best_estimator_

# 테스트 데이터에 대한 예측 수행
rf_pred = best_rf_clf.predict(x_test)

In [15]:
# 임계값 설정
threshold = 0.25
rf_pred = (rf_pred_proba[:, 1] > threshold).astype(int)

# 성능 평가
print("랜덤포레스트")
get_clf_eval(y_test, rf_pred)

랜덤포레스트
오차행렬
[[1099   64]
 [   1    4]]
정확도: 0.9443, 정밀도 : 0.0588, 재현율:0.8000,F1 스코어:0.1096
ROC 스코어: 0.8725, PR score : 0.0479


In [16]:
# 최적의 모델과 하이퍼파라미터 가져오기
best_rf_clf = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

Best Hyperparameters: {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 300}


##### 2. LogisticRegression

In [17]:
# 로지스틱 회귀 모델
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
lr_clf.fit(x_resampled, y_resampled)
lr_pred = lr_clf.predict(x_test)
lr_pred_proba = lr_clf.predict_proba(x_test)

In [18]:
print("로지스틱")
get_clf_eval(y_test, lr_pred)

로지스틱
오차행렬
[[1121   42]
 [   1    4]]
정확도: 0.9632, 정밀도 : 0.0870, 재현율:0.8000,F1 스코어:0.1569
ROC 스코어: 0.8819, PR score : 0.0704


In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

# 그리드서치를 위한 하이퍼파라미터 그리드 설정
param_grid = {
    'C': [0.001, 0.01, 0.1, 0.2, 0.3, 0.5, 1.0, 10.0],
    'penalty': ['l1', 'l2']
}

# 로지스틱 회귀 모델 생성
logistic_clf = LogisticRegression()

# 그리드서치 수행
grid_search = GridSearchCV(logistic_clf, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_resampled, y_resampled)

# 최적의 모델과 하이퍼파라미터 가져오기
best_logistic_clf = grid_search.best_estimator_

# 예측 확률 계산
logistic_pred_proba = best_logistic_clf.predict_proba(x_test)

In [20]:
# 임계값 설정 (예시로 0.5 사용)
threshold = 0.55
logistic_pred = (logistic_pred_proba[:, 1] > threshold).astype(int)

# 성능 평가
print("로지스틱")
get_clf_eval(y_test, logistic_pred)

로지스틱
오차행렬
[[1127   36]
 [   1    4]]
정확도: 0.9683, 정밀도 : 0.1000, 재현율:0.8000,F1 스코어:0.1778
ROC 스코어: 0.8845, PR score : 0.0809


In [21]:
# 최적의 모델과 하이퍼파라미터 가져오기
best_logistic_clf = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

Best Hyperparameters: {'C': 0.5, 'penalty': 'l2'}


##### 3. SVM

In [22]:
# SVM 모형 구현
from sklearn import svm

svm_clf = svm.SVC(kernel='linear', probability=True)  # 선형 SVM 모델 생성
svm_clf.fit(x_resampled, y_resampled)  # 훈련 데이터를 이용하여 모델 훈련
# 테스트 데이터를 사용하여 예측
svm_pred = svm_clf.predict(x_test)
svm_pred_proba = svm_clf.predict_proba(x_test)

In [23]:
print("SVM")
get_clf_eval(y_test, svm_pred)

SVM
오차행렬
[[1114   49]
 [   0    5]]
정확도: 0.9580, 정밀도 : 0.0926, 재현율:1.0000,F1 스코어:0.1695
ROC 스코어: 0.9789, PR score : 0.0926


In [49]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report

# RandomizedSearchCV를 사용하여 최적의 하이퍼파라미터 찾기
param_grid = {
    'C': [0.001, 0.01, 0.1, 1.0, 10.0],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}
svm_clf = SVC(probability=True)
random_search = RandomizedSearchCV(svm_clf, param_distributions=param_grid, n_iter=10, cv=5, scoring='accuracy', random_state=42)
random_search.fit(x_resampled, y_resampled)

# 최적의 모델과 하이퍼파라미터 가져오기
best_svm_clf = random_search.best_estimator_

# 예측 확률 계산
svm_pred_proba = best_svm_clf.predict_proba(x_test)

In [25]:
# 임계값 설정 (예시로 0.5 사용)
threshold = 0.4
svm_pred = (svm_pred_proba[:, 1] > threshold).astype(int)

# 성능 평가
print("SVM")
get_clf_eval(y_test, svm_pred)

SVM
오차행렬
[[1132   31]
 [   1    4]]
정확도: 0.9726, 정밀도 : 0.1143, 재현율:0.8000,F1 스코어:0.2000
ROC 스코어: 0.8867, PR score : 0.0923


In [50]:
# 최적의 모델과 하이퍼파라미터 가져오기
best_svm_clf = random_search.best_estimator_
best_params = random_search.best_params_
print("Best Hyperparameters:", best_params)

Best Hyperparameters: {'kernel': 'linear', 'gamma': 'auto', 'C': 10.0}


##### 4. KNN

In [27]:
# KNN 모형 구현
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=5)
knn_clf.fit(x_resampled, y_resampled)
knn_pred = knn_clf.predict(x_test)
knn_pred_proba = knn_clf.predict_proba(x_test)

In [28]:
print("knn")
get_clf_eval(y_test, knn_pred)

knn
오차행렬
[[1088   75]
 [   1    4]]
정확도: 0.9349, 정밀도 : 0.0506, 재현율:0.8000,F1 스코어:0.0952
ROC 스코어: 0.8678, PR score : 0.0414


In [52]:
# RandomizedSearchCV를 사용하여 최적의 하이퍼파라미터 찾기
param_grid = {
    'n_neighbors': [1, 3, 5, 7, 9, 11, 13],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'p': [1, 2]  # 1은 맨해튼 거리, 2는 유클리디언 거리
}
knn_clf = KNeighborsClassifier()
random_search = RandomizedSearchCV(knn_clf, param_distributions=param_grid, n_iter=10, cv=5, scoring='accuracy', random_state=42)
random_search.fit(x_resampled, y_resampled)

# 최적의 모델과 하이퍼파라미터 가져오기
best_knn_clf = random_search.best_estimator_

# 예측 확률 계산
knn_pred_proba = best_knn_clf.predict_proba(x_test)

In [30]:
# 임계값 설정
threshold = 0.3
knn_pred = (knn_pred_proba[:, 1] > threshold).astype(int)

# 성능 평가
print("KNN")
get_clf_eval(y_test, knn_pred)

KNN
오차행렬
[[1060  103]
 [   1    4]]
정확도: 0.9110, 정밀도 : 0.0374, 재현율:0.8000,F1 스코어:0.0714
ROC 스코어: 0.8557, PR score : 0.0308


In [53]:
# 최적의 모델과 하이퍼파라미터 가져오기
best_knn_clf = random_search.best_estimator_
best_params = random_search.best_params_
print("Best Hyperparameters:", best_params)

Best Hyperparameters: {'weights': 'distance', 'p': 1, 'n_neighbors': 5, 'algorithm': 'kd_tree'}


##### 5. LGBM

In [32]:
# LGBM 모형 구현
import lightgbm as lgb

lgb_model = lgb.LGBMClassifier()
lgb_model.fit(x_resampled, y_resampled)
# 테스트 데이터를 사용하여 예측
lgb_pred = lgb_model.predict(x_test)
lgb_pred_proba = lgb_model.predict_proba(x_test)

[LightGBM] [Info] Number of positive: 54, number of negative: 180
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000371 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 903
[LightGBM] [Info] Number of data points in the train set: 234, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.230769 -> initscore=-1.203973
[LightGBM] [Info] Start training from score -1.203973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


In [33]:
print("LGBM")
get_clf_eval(y_test, lgb_pred)

LGBM
오차행렬
[[1162    1]
 [   5    0]]
정확도: 0.9949, 정밀도 : 0.0000, 재현율:0.0000,F1 스코어:0.0000
ROC 스코어: 0.4996, PR score : 0.0043


In [54]:
from sklearn.model_selection import GridSearchCV
from lightgbm import LGBMClassifier

# 그리드서치를 위한 하이퍼파라미터 그리드 설정
param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [3, 5, 7],
    'min_child_weight': [1, 3, 5]
}

# LGBMClassifier 모델 생성
lgbm_clf = LGBMClassifier()

# 그리드서치 수행
grid_search = GridSearchCV(lgbm_clf, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_resampled, y_resampled)

# 최적의 모델과 하이퍼파라미터 가져오기
best_lgbm_clf = grid_search.best_estimator_

# 예측 확률 계산
lgbm_pred = best_lgbm_clf.predict(x_test)
lgbm_pred_proba = best_lgbm_clf.predict_proba(x_test)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 

In [35]:
# 임계값 설정
threshold = 0.1
lgb_pred = (lgb_pred_proba[:, 1] > threshold).astype(int)

# 성능 평가
print("LGBM")
get_clf_eval(y_test, lgb_pred)

LGBM
오차행렬
[[1140   23]
 [   4    1]]
정확도: 0.9769, 정밀도 : 0.0417, 재현율:0.2000,F1 스코어:0.0690
ROC 스코어: 0.5901, PR score : 0.0118


In [55]:
# 최적의 모델과 하이퍼파라미터 가져오기
best_lgbm_clf = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

Best Hyperparameters: {'learning_rate': 0.01, 'max_depth': 3, 'min_child_weight': 3, 'n_estimators': 300}


##### 6. xgboost

In [37]:
# xgboost 모형 구현
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb ## XGBoost 불러오기
from xgboost import plot_importance

xgb_wrapper = XGBClassifier()

xgb_wrapper.fit(x_resampled, y_resampled, verbose = True)


xgb_pred = xgb_wrapper.predict(x_test)
xgb_pred_proba = xgb_wrapper.predict_proba(x_test)

In [38]:
print("xgb")
get_clf_eval(y_test, xgb_pred)

xgb
오차행렬
[[1154    9]
 [   4    1]]
정확도: 0.9889, 정밀도 : 0.1000, 재현율:0.2000,F1 스코어:0.1333
ROC 스코어: 0.5961, PR score : 0.0234


In [39]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier

# 그리드서치를 위한 하이퍼파라미터 그리드 설정
param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [3, 5, 7],
    'min_child_weight': [1, 3, 5]
}

# XGBClassifier 모델 생성
xgb_clf = XGBClassifier()

# 그리드서치 수행
grid_search = GridSearchCV(xgb_clf, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_resampled, y_resampled)

# 최적의 모델과 하이퍼파라미터 가져오기
best_xgb_clf = grid_search.best_estimator_

# 테스트 데이터에 대한 예측 수행
xgb_pred = best_xgb_clf.predict(x_test)
xgb_pred_proba = best_xgb_clf.predict_proba(x_test)

In [40]:
# 임계값 설정
threshold = 0.1
xgb_pred = (xgb_pred_proba[:, 1] > threshold).astype(int)

# 성능 평가
print("xgboost")
get_clf_eval(y_test, lgb_pred)

xgboost
오차행렬
[[1140   23]
 [   4    1]]
정확도: 0.9769, 정밀도 : 0.0417, 재현율:0.2000,F1 스코어:0.0690
ROC 스코어: 0.5901, PR score : 0.0118


In [41]:
# 최적의 모델과 하이퍼파라미터 가져오기
best_xgb_clf = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

Best Hyperparameters: {'learning_rate': 0.01, 'max_depth': 3, 'min_child_weight': 1, 'n_estimators': 300}


#### 7. catboost

In [42]:
!pip install catboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.5/98.5 MB 5.6 MB/s eta 0:00:00


In [43]:
from catboost import CatBoostClassifier

catboost_model = CatBoostClassifier()
catboost_model.fit(x_resampled, y_resampled)
# 테스트 데이터를 사용하여 예측
catboost_pred = catboost_model.predict(x_test)
catboost_pred_proba = catboost_model.predict_proba(x_test)

Learning rate set to 0.005541
0:	learn: 0.6850727	total: 50.9ms	remaining: 50.8s
1:	learn: 0.6788387	total: 53.5ms	remaining: 26.7s
2:	learn: 0.6720863	total: 56.1ms	remaining: 18.7s
3:	learn: 0.6652404	total: 59.1ms	remaining: 14.7s
4:	learn: 0.6590849	total: 62ms	remaining: 12.3s
5:	learn: 0.6537162	total: 64.6ms	remaining: 10.7s
6:	learn: 0.6466814	total: 67.2ms	remaining: 9.53s
7:	learn: 0.6412125	total: 69.9ms	remaining: 8.66s
8:	learn: 0.6343669	total: 72.6ms	remaining: 7.99s
9:	learn: 0.6278488	total: 75.4ms	remaining: 7.46s
10:	learn: 0.6222492	total: 78.4ms	remaining: 7.05s
11:	learn: 0.6160455	total: 81.6ms	remaining: 6.72s
12:	learn: 0.6108105	total: 84.5ms	remaining: 6.42s
13:	learn: 0.6046362	total: 87.5ms	remaining: 6.16s
14:	learn: 0.5989924	total: 90.6ms	remaining: 5.95s
15:	learn: 0.5934850	total: 93.7ms	remaining: 5.76s
16:	learn: 0.5874901	total: 96.8ms	remaining: 5.6s
17:	learn: 0.5822072	total: 99.9ms	remaining: 5.45s
18:	learn: 0.5764529	total: 103ms	remaining: 5.

In [44]:
print("catboost")
get_clf_eval(y_test, catboost_pred)

catboost
오차행렬
[[1159    4]
 [   5    0]]
정확도: 0.9923, 정밀도 : 0.0000, 재현율:0.0000,F1 스코어:0.0000
ROC 스코어: 0.4983, PR score : 0.0043


In [45]:
from sklearn.model_selection import GridSearchCV
from catboost import CatBoostClassifier

# 그리드서치를 위한 하이퍼파라미터 그리드 설정
param_grid = {
    'iterations': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1, 0.3],
    'depth': [3, 5, 7],
    'l2_leaf_reg': [1, 3, 5]
}

# CatBoostClassifier 모델 생성
catboost_clf = CatBoostClassifier()

# 그리드서치 수행
grid_search = GridSearchCV(catboost_clf, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_resampled, y_resampled)

# 최적의 모델과 하이퍼파라미터 가져오기
best_catboost_clf = grid_search.best_estimator_

# 테스트 데이터에 대한 예측 수행
catboost_pred = best_catboost_clf.predict(x_test)
catboost_pred_proba = best_catboost_clf.predict_proba(x_test)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
200:	learn: 0.1437270	total: 943ms	remaining: 465ms
201:	learn: 0.1431340	total: 948ms	remaining: 460ms
202:	learn: 0.1424702	total: 952ms	remaining: 455ms
203:	learn: 0.1419221	total: 957ms	remaining: 450ms
204:	learn: 0.1413287	total: 961ms	remaining: 445ms
205:	learn: 0.1406319	total: 972ms	remaining: 443ms
206:	learn: 0.1399854	total: 980ms	remaining: 440ms
207:	learn: 0.1396848	total: 988ms	remaining: 437ms
208:	learn: 0.1389501	total: 994ms	remaining: 433ms
209:	learn: 0.1384760	total: 998ms	remaining: 428ms
210:	learn: 0.1378400	total: 1s	remaining: 423ms
211:	learn: 0.1372846	total: 1.01s	remaining: 418ms
212:	learn: 0.1366800	total: 1.01s	remaining: 413ms
213:	learn: 0.1358475	total: 1.01s	remaining: 408ms
214:	learn: 0.1354349	total: 1.02s	remaining: 403ms
215:	learn: 0.1347992	total: 1.02s	remaining: 398ms
216:	learn: 0.1341406	total: 1.03s	remaining: 395ms
217:	learn: 0.1335530	total: 1.04s	remaining: 392ms
218:	learn: 0.1328267	total: 1.

In [46]:
# 임계값 설정
threshold = 0.3
catboost_pred = (catboost_pred_proba[:, 1] > threshold).astype(int)

# 성능 평가
print("catboost")
get_clf_eval(y_test, catboost_pred)

catboost
오차행렬
[[1134   29]
 [   4    1]]
정확도: 0.9717, 정밀도 : 0.0333, 재현율:0.2000,F1 스코어:0.0571
ROC 스코어: 0.5875, PR score : 0.0101


In [47]:
# 최적의 모델과 하이퍼파라미터 가져오기
best_catboost_clf = grid_search.best_estimator_
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

Best Hyperparameters: {'depth': 5, 'iterations': 100, 'l2_leaf_reg': 3, 'learning_rate': 0.3}
